# Generated by Django 5.2.8 on 2025-11-21 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_code', models.CharField(help_text='Manual unique code (e.g. B1-F1-N01)', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, help_text='Human readable name', max_length=128)),
                ('building', models.CharField(blank=True, max_length=128)),
                ('floor_level', models.IntegerField(blank=True, help_text='Integer floor level', null=True)),
                ('type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('OFFICE', 'Office'), ('JUNCTION', 'Junction'), ('STAIR_ENTRY', 'Stair Entry'), ('STAIR_EXIT', 'Stair Exit'), ('ELEVATOR', 'Elevator'), ('DESTINATION', 'Destination')], default='JUNCTION', max_length=32)),
                ('panorama_image', models.ImageField(blank=True, null=True, upload_to='panoramas/%Y/%m/%d/')),
                ('qr_code_string', models.TextField(blank=True, help_text='String embedded in a location QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'floor_level', 'node_code'],
                'indexes': [models.Index(fields=['node_code'], name='rec_node_node_co_0a95cd_idx'), models.Index(fields=['building', 'floor_level'], name='rec_node_buildin_ac0a27_idx')],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='Distance in meters (e.g. 5.5)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_staircase', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_ending', to='rec.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_starting', to='rec.node')),
            ],
            options={
                'ordering': ['start_node__node_code', 'end_node__node_code'],
                'constraints': [models.UniqueConstraint(fields=('start_node', 'end_node'), name='unique_edge')],
            },
        ),
    ]
