# Generated by Django 5.2 on 2025-11-21 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor_level', models.IntegerField()),
                ('type_of_node', models.CharField(default='room', max_length=255)),
                ('image360', models.URLField(blank=True, null=True)),
                ('qrcode_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('compass_angle', models.FloatField(help_text='Compass angle in degrees (0-360) from from_node to to_node', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staircase', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_edges', to='rec.nodes')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_edges', to='rec.nodes')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Text label to display for this hotspot', max_length=255)),
                ('yaw', models.FloatField(help_text='Horizontal rotation in degrees (-180..180)', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('pitch', models.FloatField(help_text='Vertical rotation in degrees (-90..90)', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('visible_radius', models.FloatField(default=10.0, help_text='Angular radius in degrees used by viewer when deciding visibility', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='rec.nodes')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_annotations', to='rec.nodes')),
            ],
            options={
                'verbose_name': 'Panorama Annotation',
                'verbose_name_plural': 'Panorama Annotations',
                'unique_together': {('panorama', 'yaw', 'pitch', 'label')},
            },
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
