# Generated by Django 5.2.8 on 2025-11-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_nodes_edges_annotation_delete_edge_delete_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='qrcode_url',
        ),
        migrations.AddField(
            model_name='nodes',
            name='qrcode',
            field=models.ImageField(blank=True, help_text='Auto-generated QR code', null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='image360',
            field=models.ImageField(blank=True, help_text='Upload 360° panorama image', null=True, upload_to='360_images/'),
        ),
    ]
