# Generated by Django 5.2.8 on 2025-11-21 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0003_remove_nodes_qrcode_url_nodes_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='map_x',
            field=models.FloatField(blank=True, help_text='X coordinate on campus map (0-100%, left to right)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='nodes',
            name='map_y',
            field=models.FloatField(blank=True, help_text='Y coordinate on campus map (0-100%, top to bottom)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.CreateModel(
            name='CampusMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Map name (e.g., "Engineering Building - Floor 1")', max_length=255)),
                ('building', models.CharField(help_text='Building name', max_length=255)),
                ('floor_level', models.IntegerField(help_text='Floor number')),
                ('blueprint_image', models.ImageField(help_text='Campus blueprint/floor plan image', upload_to='campus_maps/')),
                ('scale_meters_per_pixel', models.FloatField(blank=True, help_text='Scale: meters per pixel (for distance calculation)', null=True)),
                ('north_rotation', models.FloatField(default=0.0, help_text='Rotation angle where North points (0° = top of image)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'floor_level'],
                'unique_together': {('building', 'floor_level')},
            },
        ),
    ]
