# Generated by Django 5.2.8 on 2025-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_nodes_map_x_nodes_map_y_campusmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusmap',
            options={'verbose_name': 'Campus Map', 'verbose_name_plural': 'Campus Maps'},
        ),
        migrations.AlterUniqueTogether(
            name='campusmap',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='campusmap',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one map should be active'),
        ),
        migrations.AlterField(
            model_name='campusmap',
            name='name',
            field=models.CharField(default='Campus Map', help_text='Map name', max_length=255),
        ),
        migrations.RemoveField(
            model_name='campusmap',
            name='building',
        ),
        migrations.RemoveField(
            model_name='campusmap',
            name='floor_level',
        ),
        migrations.RemoveField(
            model_name='campusmap',
            name='north_rotation',
        ),
    ]
